### ISSUE TITLE
The code may be missing 'le_conv.py' and 'score.py'

### ISSUE THREAD

**Issue by Yiikea** [zhangyubrain/DGCN#2]
Dear author, when I use your code to reproduce the results of the article, I find that there is no le_conv and score code in the net folder. If possible, can you copy one for me? I just want to refer to your code, thanks!

Console:
ModuleNotFoundError: No module named 'net.le_conv'
ModuleNotFoundError: No module named 'net.score'

**Comment by alienx-zero** [comment]
I upload these two py files. In the last version of main.py, it might not import the function from these files in the modeling.

**Comment by Yiikea** [comment]
Thanks a lot！
